services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/saved_logs:/app/saved_logs
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: wcl-analyzer-dev